// Mesmo seed de câmeras do app macOS (CamerasSeed.swift)
const CAMERAS_SEED = [
  { nome: "NY Hudson Valley, câmera R8-001", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_001/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-002", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_002/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-003", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_003/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-004", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_004/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-005", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_005/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-006", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_006/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-007", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_007/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-008", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_008/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-009", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_009/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-018", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_018/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-021", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_021/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-031", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_031/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-032", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_032/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-037", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_037/playlist.m3u8" },
  { nome: "NY Hudson Valley, câmera R8-038", categoria: "Hudson Valley (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R8_038/playlist.m3u8" },
  { nome: "NY North Country, câmera R7-001", categoria: "North Country (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R7_001/playlist.m3u8" },
  { nome: "NY North Country, câmera R7-003", categoria: "North Country (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R7_003/playlist.m3u8" },
  { nome: "NY North Country, câmera R7-004", categoria: "North Country (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R7_004/playlist.m3u8" },
  { nome: "NY North Country, câmera R7-005", categoria: "North Country (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R7_005/playlist.m3u8" },
  { nome: "NY North Country, câmera R7-006", categoria: "North Country (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R7_006/playlist.m3u8" },
  { nome: "NY North Country, câmera R7-007", categoria: "North Country (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R7_007/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-005", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_005/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-011", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_011/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-013", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_013/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-015", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_015/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-016", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_016/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-017", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_017/playlist.m3u8" },
  { nome: "NY Southern Tier, câmera R6-019", categoria: "Southern Tier (NY)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_019/playlist.m3u8" },
  { nome: "NY, I-86 Exit 54 @ NY-13", categoria: "Trânsito / Demo (DOT público)", url: "https://s7.nysdot.skyvdn.com:443/rtplive/R6_030/playlist.m3u8" },
  { nome: "LA, Shreveport (shr-cam-030)", categoria: "Trânsito / Demo (DOT público)", url: "https://ITSStreamingBR2.dotd.la.gov/public/shr-cam-030.streams/playlist.m3u8" },
]
